### ISSUE TITLE
Official support for 8.0 and 8.1 

### ISSUE THREAD

**Issue by faroit** [sonyxperiadev/device-sony-tama#1]
I know that this is probably the wrong channel of communication but I am curious when and if Sony Mobile

* officially supports the XZ2 and XZ2 compact as part of their open device program
* will update the platform to 8.1 to address some issues regarding the [touch screen sensitivity](https://forum.xda-developers.com/xperia-xz2-compact/how-to/screen-sensitivity-issue-read-game-xz2-t3775939)

**Comment by jerpelea** [comment]
Those devices will be annouced in the program as soon as they are ready
